---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karthikdeployment
  labels:
    app: karthiknginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karthiknginx
  template:
    metadata:
      labels:
        app: karthiknginx
    spec:
      containers:
      - name: karthiknginx
        image: raveendrareddy/learning:latest-2
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: secret-tiger-docker
