apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: raveendrareddy/learning:latest-2
        ports:
        - containerPort: 80
      imagePullSecrets:
       - name: secret-tiger-docker
