apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: raveendrareddy/learning:latest-2
      ports:
        - name: web
          containerPort: 80
          protocol: TCP  